# AUTO-GENERATED by tools/make_ablation_configs.py — Table 8 ablation cell.
# attention=symattention  pe=rpe  use_stn=True  direction=r2l
_base_ = '../retinanet_r50_fpn_tbx11k_512.py'

model = dict(
    neck=dict(
        type='SASFPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,
        add_extra_convs='on_input',
        num_outs=5,
        sas=dict(
            attention='symattention',
            pe='rpe',
            use_stn=True,
            direction='r2l',
            num_heads=8,
            num_points=4,
            offset_scale=0.1,
        )))
