#!/usr/bin/env python
"""Generate the Table-8 ablation configs (plan.md Phase 8).

Emits one mmdet config per ablation cell into ``configs/ablation/``. Each config inherits the
RetinaNet baseline and swaps in an ``SASFPN`` neck with the cell's SAS settings. The baseline
row ("No attention / No PE") is just ``configs/retinanet_r50_fpn_tbx11k_512.py`` — no file is
generated for it.

Matrix (12 cells):
    attention in {vanilla, symattention}
      x  pe in {ape, rpe, spe_nostn(l2r), spe_nostn(r2l), spe(l2r), spe(r2l)}

Run:  python tools/make_ablation_configs.py
This only writes text files (no torch), so it is safe to run locally.
"""

from __future__ import annotations

import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.normpath(os.path.join(HERE, "..", "configs", "ablation"))

NECK_TEMPLATE = """# AUTO-GENERATED by tools/make_ablation_configs.py — Table 8 ablation cell.
# attention={attention}  pe={pe}  use_stn={use_stn}  direction={direction}
_base_ = '../retinanet_r50_fpn_tbx11k_512.py'

model = dict(
    neck=dict(
        type='SASFPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,
        add_extra_convs='on_input',
        num_outs=5,
        sas=dict(
            attention='{attention}',
            pe='{pe}',
            use_stn={use_stn},
            direction='{direction}',
            num_heads=8,
            num_points=4,
            offset_scale=0.1,
        )))
"""


def cells():
    for attention in ("vanilla", "symattention"):
        # PE variants that do not involve symmetry direction / STN:
        yield attention, "ape", True, "r2l", f"abl_{attention}_ape.py"
        yield attention, "rpe", True, "r2l", f"abl_{attention}_rpe.py"
        # SPE variants: with/without STN, both directions
        for direction in ("l2r", "r2l"):
            yield attention, "spe", False, direction, f"abl_{attention}_spe_nostn_{direction}.py"
        for direction in ("l2r", "r2l"):
            yield attention, "spe", True, direction, f"abl_{attention}_spe_stn_{direction}.py"


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    written = []
    for attention, pe, use_stn, direction, fname in cells():
        text = NECK_TEMPLATE.format(attention=attention, pe=pe,
                                    use_stn=use_stn, direction=direction)
        path = os.path.join(OUT_DIR, fname)
        with open(path, "w") as f:
            f.write(text)
        written.append(fname)
    # a small README describing run order (most-informative cells first)
    readme = os.path.join(OUT_DIR, "README.md")
    with open(readme, "w") as f:
        f.write(
            "# Table 8 ablation configs (auto-generated)\n\n"
            "Baseline (No/No) = `../retinanet_r50_fpn_tbx11k_512.py` (no file here).\n\n"
            "Suggested run order (most-informative first, per plan.md Phase 8):\n"
            "1. baseline (retinanet config)\n"
            "2. `abl_vanilla_ape.py`\n"
            "3. `abl_symattention_ape.py`\n"
            "4. `abl_symattention_spe_stn_r2l.py`  (= the full SymFormer neck)\n"
            "5. STN pair: `abl_symattention_spe_nostn_r2l.py` vs `abl_symattention_spe_stn_r2l.py`\n"
            "6. direction pair: `..._spe_stn_l2r.py` vs `..._spe_stn_r2l.py`\n"
            "7. the remaining cells\n\n"
            "All configs: " + ", ".join(f"`{w}`" for w in written) + "\n"
        )
    print(f"Wrote {len(written)} ablation configs + README to {OUT_DIR}")
    for w in written:
        print("  ", w)


if __name__ == "__main__":
    main()
